# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT

# This yml file is used to test the Dockerfile locally. see Readme for more details.

server:
  port: 8080
spring:
  datasource:
    url: "jdbc:postgresql://identifier-registry-db:5432/identifier-registry-db"
    username: "postgres"
    password: "secret"
  jpa:
    properties:
      hibernate:
        ddl-auto: create
jeap:
  monitor:
    prometheus:
      password: "{noop}test"
      user: "prometheus"

logging:
  level:
    ch.admin.bit.jeap: DEBUG
    ch.admin.bj.swiyu: DEBUG
